# Generated by Django 4.0.1 on 2022-01-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='striped_url',
            field=models.URLField(max_length=40, unique=True),
        ),
    ]
