# Generated by Django 4.0.1 on 2022-01-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_url_striped_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='striped_url',
            field=models.URLField(max_length=40),
        ),
    ]
